---
language: ruby
cache:
  bundler: true
  directories:
  - $HOME/.cargo
  - $TRAVIS_BUILD_DIR/target
rvm:
  - 2.6.3
before_install:
  - curl -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
  - gem install bundler
